import { google, youtube_v3 } from "googleapis";
import { VideoEntry } from "./types";
import { parseDateFromTitle } from "./parser";

/**
 * Builds an authenticated YouTube client using OAuth2 credentials stored in
 * environment variables.
 */
export function buildYouTubeClient(): youtube_v3.Youtube {
  const oauth2Client = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET,
    process.env.YOUTUBE_REDIRECT_URI ?? "urn:ietf:wg:oauth:2.0:oob"
  );

  oauth2Client.setCredentials({
    refresh_token: process.env.YOUTUBE_REFRESH_TOKEN,
  });

  return google.youtube({ version: "v3", auth: oauth2Client });
}

/**
 * Retrieves the "uploads" playlist ID for a given channel.
 */
export async function getUploadsPlaylistId(
  channelId: string,
  yt: youtube_v3.Youtube
): Promise<string> {
  const res = await yt.channels.list({
    part: ["contentDetails"],
    id: [channelId],
  });

  const uploadsId =
    res.data.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;
  if (!uploadsId) {
    throw new Error(
      `Could not find uploads playlist for channel "${channelId}". ` +
        `Verify the channel ID is valid and accessible.`
    );
  }
  return uploadsId;
}

/**
 * Fetches all videos from an uploads playlist, handling pagination.
 */
export async function fetchVideosFromPlaylist(
  uploadsPlaylistId: string,
  channelId: string,
  yt: youtube_v3.Youtube
): Promise<VideoEntry[]> {
  const videos: VideoEntry[] = [];
  let pageToken: string | undefined;
  let parsedCount = 0;
  let fallbackCount = 0;

  do {
    const res = await yt.playlistItems.list({
      part: ["snippet"],
      playlistId: uploadsPlaylistId,
      maxResults: 50,
      pageToken,
    });

    for (const item of res.data.items ?? []) {
      const snippet = item.snippet;
      if (!snippet) continue;

      const videoId = snippet.resourceId?.videoId;
      const title = snippet.title ?? "";
      const publishedAt = snippet.publishedAt ?? new Date().toISOString();

      if (!videoId) continue;

      const parsedDate = parseDateFromTitle(title);
      let sortDate: Date;
      let usedParsedDate: boolean;

      if (parsedDate) {
        sortDate = parsedDate;
        usedParsedDate = true;
        parsedCount++;
      } else {
        sortDate = new Date(publishedAt);
        usedParsedDate = false;
        fallbackCount++;
      }

      videos.push({ videoId, title, publishedAt, channelId, sortDate, usedParsedDate });
    }

    pageToken = res.data.nextPageToken ?? undefined;
  } while (pageToken);

  console.log(
    `  Fetched ${videos.length} videos from uploads playlist ${uploadsPlaylistId} ` +
      `(${parsedCount} with parsed dates, ${fallbackCount} using publishedAt fallback)`
  );

  return videos;
}

/**
 * Finds an existing playlist with the given title owned by the authenticated
 * user, or creates a new one if it does not exist.
 * Returns the playlist ID.
 */
export async function findOrCreatePlaylist(
  playlistName: string,
  yt: youtube_v3.Youtube
): Promise<string> {
  // Search the user's playlists for one with a matching title.
  let pageToken: string | undefined;

  do {
    const res = await yt.playlists.list({
      part: ["snippet"],
      mine: true,
      maxResults: 50,
      pageToken,
    });

    for (const playlist of res.data.items ?? []) {
      if (playlist.snippet?.title === playlistName) {
        console.log(
          `Reusing existing playlist "${playlistName}" (ID: ${playlist.id})`
        );
        return playlist.id!;
      }
    }

    pageToken = res.data.nextPageToken ?? undefined;
  } while (pageToken);

  // No match found – create a new playlist.
  const created = await yt.playlists.insert({
    part: ["snippet", "status"],
    requestBody: {
      snippet: {
        title: playlistName,
        description: "Auto-generated by youtube-multi-channel-feed",
      },
      status: { privacyStatus: "private" },
    },
  });

  const newId = created.data.id;
  if (!newId) {
    throw new Error("Failed to create playlist – no ID returned by API.");
  }

  console.log(`Created new playlist "${playlistName}" (ID: ${newId})`);
  return newId;
}

/**
 * Fetches the set of video IDs already present in a playlist.
 */
export async function getExistingPlaylistVideoIds(
  playlistId: string,
  yt: youtube_v3.Youtube
): Promise<Set<string>> {
  const existing = new Set<string>();
  let pageToken: string | undefined;

  do {
    const res = await yt.playlistItems.list({
      part: ["snippet"],
      playlistId,
      maxResults: 50,
      pageToken,
    });

    for (const item of res.data.items ?? []) {
      const vid = item.snippet?.resourceId?.videoId;
      if (vid) existing.add(vid);
    }

    pageToken = res.data.nextPageToken ?? undefined;
  } while (pageToken);

  return existing;
}

/**
 * Adds a single video to a playlist.
 */
export async function addVideoToPlaylist(
  videoId: string,
  playlistId: string,
  yt: youtube_v3.Youtube
): Promise<void> {
  await yt.playlistItems.insert({
    part: ["snippet"],
    requestBody: {
      snippet: {
        playlistId,
        resourceId: { kind: "youtube#video", videoId },
      },
    },
  });
}
